version: "3.7"

services:
    # image project
    app:
        container_name: setup-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: setup/laradocker
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        container_name: setup-nginx
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    mysql:
        container_name: setup-mysql
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    # queue
    queue:
        container_name: setup-queue
        image: setup/laradocker
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # redis
    redis:
        container_name: setup-redis
        image: redis:latest
        networks:
            - laravel

    # phpmyadmin
    phpmyadmin:
        container_name: setup-phpmyadmin
        image: phpmyadmin
        ports:
            - 81:80
        environment:
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
